import re

from rdflib.graph import Dataset, Graph
from rdflib.term import BNode, URIRef
from rdflib.util import guess_format

from nanopub.definitions import ARTIFACTCODE_PLACEHOLDER, NP_PREFIX, NP_TEMP_PREFIX
from nanopub.trustyuri.TrustyUriUtils import is_trusty_uri, TRUSTY_ARTIFACT_RE


def get_trustyuri(resource, base_uri, hashstr, bnodemap):
    """Most of the work done to normalize URIs happens here"""
    if resource is None:
        return None
    np_uri = get_str(base_uri).decode('utf-8')
    separator = "/"
    # baseuri passed is the np namespace, np_uri is the nanopub URI without trailing # or /
    if np_uri.endswith('#') or np_uri.endswith('/'):
        separator = np_uri[-1]
        np_uri = np_uri[:-1]
    # Extract the trusty artifact if present, or remove the trailing / if trusty not present.
    # Use regex to find the trusty code so non-standard schemes like
    # "base#id.RAxxxx" (where the code is not the last /-segment) are handled.
    base_str = str(base_uri).rstrip("/#")
    m = re.search(r'RA[A-Za-z0-9_\-]{40,}', base_str)
    if m:
        prefix = base_str[:m.start()]
    elif is_trusty_uri(base_uri):
        prefix = base_str.rsplit("/", 1)[0] + "/"
    else:
        prefix = "/".join(base_uri.split('/')[:-1]) + '/'
    if str(base_uri).startswith(NP_TEMP_PREFIX):
        prefix = NP_PREFIX
    if isinstance(resource, URIRef):
        suffix = get_suffix(resource, base_uri)
        if get_str(resource).decode('utf-8') == np_uri:
            return str(f"{prefix}{hashstr}")
        if suffix is None and not get_str(resource).decode('utf-8') == get_str(base_uri).decode('utf-8'):
            # URI outside the nanopub's own namespace (e.g. a concept minted in a
            # custom namespace). It may carry the artifact-code placeholder, or —
            # when verifying an already-signed nanopub — this nanopub's trusty code.
            # Substitute either with `hashstr` so it is part of the hash (and gets
            # the real code substituted in when applying the trusty artifact).
            # See issue #232.
            res_str = str(resource).replace(ARTIFACTCODE_PLACEHOLDER, hashstr)
            base_code = re.search(r'RA[A-Za-z0-9_\-]{40,}', str(base_uri))
            if base_code:
                # Only blank THIS nanopub's code; references to other trusty
                # nanopubs (different codes) are left untouched.
                res_str = res_str.replace(base_code.group(0), hashstr)
            return res_str
        if suffix is None or suffix == "":
            return str(f"{prefix}{hashstr}")
        # External trusty URI or external reference — leave untouched
        if TRUSTY_ARTIFACT_RE.match(suffix.split("/", 1)[0].split("#", 1)[0]):
            return str(resource)

        # When base_uri has no trailing separator (e.g. disgenet-style
        # "RAxxxx130_head"), the suffix is directly appended — use no
        # separator.  For standard namespaces ending with "/" or "#" the
        # separator was already captured above from the base_uri itself.
        base_uri_str = get_str(base_uri).decode('utf-8')
        if not (base_uri_str.endswith('#') or base_uri_str.endswith('/')):
            if suffix[0] in ('#', '/'):
                separator = suffix[0]
            else:
                separator = ""
        clean_suffix = suffix.lstrip("/#")
        return str(f"{prefix}{hashstr}{separator}{clean_suffix}")
    if isinstance(resource, BNode):
        # NOTE: bnodes are replaced in nanopub.py by _replace_blank_nodes() most of the time
        bnode_unnamed = re.match(r'^[a-zA-Z0-9]{33}$', str(resource))
        # Check if BNode in the form of N2b80343001e94f48bdee0901be566ebb
        # Which means it was automatically generated by rdflib: we use a number in this case
        if bnode_unnamed:
            n = get_bnode_number(resource, bnodemap)
            np_uri = str(f"{prefix}{hashstr}")
            return str(np_uri + "#_" + str(n))
        else:
            # If the user gave a specific name to the bnode with rdflib
            return str(f"{prefix}{hashstr}" + "#_" + str(resource))
    else:
        return None


def get_suffix(plainuri, baseuri):
    p = get_str(plainuri)
    b = get_str(baseuri)
    if p == b:
        return None
    if p.startswith(b):
        return p[len(b):].decode('utf-8')
    return None


def normalize(uri, hashstr):
    if hashstr is None:
        return get_str(uri)
    try:
        return re.sub(hashstr, " ", str(uri))
    except Exception:
        return re.sub(hashstr.decode('utf-8'), " ", str(uri))


def get_bnode_number(bnode, bnodemap):
    i = get_str(bnode)
    if i not in bnodemap.keys():
        n = len(bnodemap) + 1
        bnodemap[i] = n
    return bnodemap[i]


def expand_baseuri(baseuri):
    s = get_str(baseuri).decode('utf-8')
    if re.match(r'.*[A-Za-z0-9\-_]', s):
        s = s + "."
    return s


def get_quads(dataset):
    quads = []
    for s, p, o, g in dataset.quads((None, None, None, None)):
        if not isinstance(g, URIRef):
            g = None
        quads.append((g, s, p, o))
    quads.sort()
    return quads


def get_dataset(quads):
    cg = Dataset()
    #     for (c, s, p, o) in quads:
    #         cg.default_context = Graph(store=cg.store, identifier=c)
    #         cg.add((s, p, o))
    cg.addN([(s, p, o, Graph(store=cg.store, identifier=c)) for (c, s, p, o) in quads])
    return cg


def get_format(filename):
    return guess_format(filename, {'xml': 'trix', 'ttl': 'turtle', 'nq': 'nquads', 'nt': 'nt', 'rdf': 'xml'})


def get_str(s):
    return s.encode('utf-8')
