name: Tests and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12.4" ]
        rdflib-version:
          - rdflib==6.3.2
          - rdflib==7.1.4
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Install UV
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with ${{ matrix.rdflib-version }}
        run: |
          uv sync --group test --group dev
          uv add ${{ matrix.rdflib-version }}

      - name: Setup nanopub profile (including RSA keys)
        run: |
          uv run np setup --orcid-id https://orcid.org/0000-0000-0000-0000 --no-publish --name test --newkeys

      - name: Test with pytest
        run: uv run pytest -v --cov

      - name: Publish coverage to Coveralls
        run: |
          uv run coverage xml
          uv run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }} - ${{ matrix.rdflib-version }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Install coveralls
        run: pip3 install --upgrade coveralls
      - name: Finished
        run: coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
